spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project-1
    username: root
    password: a1b2c3!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:

    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true